apiVersion: v1
kind: Service
metadata:
  name: trdl-service
  labels:
    app: trdl
spec:
  type: LoadBalancer
  selector:
    app: trdl
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80

